on:
  push:
    branches-ignore:
      - "gh-readonly-queue/**"
  pull_request_target:
  merge_group:
  workflow_dispatch:

name: Clippy check
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --all --features cortex-m/critical-section-single-core -- --deny warnings
